#!/bin/bash

# Iniciar sxhkd si no está en ejecución
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/bspwm/cambiar_bordes &
feh --bg-fill --randomize ~/.wall/* &
picom &

# Configuraciones de BSPWM
bspc config border_width         3.5
bspc config window_gap           3
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false

# Detectar los monitores conectados
monitores=($(xrandr --listmonitors | grep -oP '\d+:\s+\K\w+'))

# Si no hay monitores conectados, salir
if [ ${#monitores[@]} -eq 0 ]; then
  echo "No se detectaron monitores conectados."
  exit 1
fi

# Asignar escritorios a los monitores detectados
if [ ${#monitores[@]} -eq 1 ]; then
  # Si hay un solo monitor, asignar todos los escritorios al primer monitor
  bspc monitor "${monitores[0]}" -d 1 2 3 4 5
else
  # Si hay más de un monitor, asignar escritorios a cada uno
  bspc monitor "${monitores[0]}" -d 1 2 3 4 5
  bspc monitor "${monitores[1]}" -d 6 7 8 9 0
fi
