#!/bin/bash

# Iniciar sxhkd si no está en ejecución
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/bspwm/cambiar_bordes &
feh --bg-fill --randomize ~/.wall/* &
picom &

# Configuraciones de BSPWM
bspc config border_width         3.5
bspc config window_gap           3
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false

# Detectar los monitores conectados usando xrandr
monitores=($(xrandr --listmonitors | grep -oP '\+*\w+-\w+' | uniq))

# Si no hay monitores conectados, salir
if [ ${#monitores[@]} -eq 0 ]; then
  echo "No se detectaron monitores conectados."
  exit 1
fi

# Asignación manual de escritorios a monitores
if [ ${#monitores[@]} -eq 1 ]; then
  # Si hay un solo monitor, asignamos escritorios 1-5 a ese monitor
  bspc monitor "${monitores[0]}" -d 1 2 3 4 5
elif [ ${#monitores[@]} -eq 2 ]; then
  # Si hay dos monitores, asignamos escritorios a cada monitor
  bspc monitor "${monitores[0]}" -d 1 2 3 4 5
  bspc monitor "${monitores[1]}" -d 6 7 8 9 0
else
  # Si hay más de dos monitores, asignamos escritorios a los primeros dos
  bspc monitor "${monitores[0]}" -d 1 2 3 4 5
  bspc monitor "${monitores[1]}" -d 6 7 8 9 0

^