#! /bin/bash

# Verificar si sxhkd no está en ejecución y arrancarlo si es necesario
pgrep -x sxhkd > /dev/null || sxhkd &
# Arrancar picom para transparencias
picom &
# Habilitar NumLock
numlockx on
# Obtener la lista de monitores disponibles
monitors=$(xrandr --query | grep " connected" | cut -d" " -f1)

# Verificar si hay un solo monitor o más
if [ $(echo "$monitors" | wc -l) -eq 1 ]; then
    # Si hay un solo monitor, asignar escritorios solo a ese monitor
    bspc monitor --remove DP-1
    bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 0
    xrandr --output HDMI-1 --primary --mode 1280x720 --pos 0x0 --rotate normal
elif [ $(echo "$monitors" | wc -l) -eq 2 ]; then
    # Si hay dos monitores, asignar escritorios a ambos monitores
    bspc monitor HDMI-1 -d 1 2 3 4 5
    bspc monitor DP-1  -d 6 7 8 9 0    
    xrandr --output HDMI-1 --primary --mode 1280x720 --pos 0x0 --rotate normal --output DP-1 --mode 1280x720 --pos 1332x0 --rotate normal
fi

#################################
# Configuraciones de BSPWM
bspc config border_width         0.1
bspc config window_gap           6
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
